#! /bin/sh
# UCLA CS 111 - Check distribution.

# Copyright 2012-2014 Paul Eggert.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C

tar xvf $1.tar.gz.tmp || exit

cd $1 || exit

old=$(ls -al | grep -v '^d') || exit
make clean || exit
new=$(ls -al | grep -v '^d') || exit

test "$old" = "$new" || {
  echo "junk in distribution"
  echo "=== old ===
$old
=== new ===
$new"
  exit 1
}

make check || exit

make clean || exit
new=$(ls -al | grep -v '^d') || exit
test "$old" = "$new" || {
  echo "'make clean' doesn't clean"
  echo "=== old ===
$old
=== new ===
$new"
  exit 1
}
